version: '3.9'

services:
  class-reminder-be:
    build: .
    container_name: class-reminder-be
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - ./config.json:/app/config.json
    depends_on:
      - rundeck
    restart: unless-stopped

  rundeck:
    image: rundeck/rundeck:SNAPSHOT
    container_name: rundeck
    ports:
      - "4440:4440"
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
      RUNDECK_SERVER_URL: http://localhost:4440
      RUNDECK_ADMIN_PASSWORD: admin
    volumes:
      - rundeck_data:/home/rundeck/server/data
    restart: unless-stopped

volumes:
  rundeck_data:
